# Generated by Django 5.0.6 on 2024-07-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_fruits.categoryproduct'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='app_fruits/products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(choices=[('$', 'USD'), ("So'm", 'UZS')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='categoryproduct',
            table=None,
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
